---
deployment:
  tasks:
    - /bin/mkdir -p /home/westbrookinterna/app-westbrook-site
    - /bin/cp -a /home/westbrookinterna/git-westbrook-site/. /home/westbrookinterna/app-westbrook-site/
    - /bin/bash -c "source /home/westbrookinterna/nodevenv/app-westbrook-site/22/bin/activate && cd /home/westbrookinterna/app-westbrook-site && npm install && npm run build"
    - /bin/mkdir -p /home/westbrookinterna/app-westbrook-site/tmp
    - /bin/touch /home/westbrookinterna/app-westbrook-site/tmp/restart.txt
