---
deployment:
  tasks:
    - export DEPLOYPATH=/home/westbrookinterna/repositories/westbrook-website/
    - /bin/bash -c "source /home/westbrookinterna/nodevenv/repositories/westbrook-website/22/bin/activate && cd $DEPLOYPATH && npm install && npm run build"
    - /bin/mkdir -p $DEPLOYPATH/tmp
    - /bin/touch $DEPLOYPATH/tmp/restart.txt
